# written by tode --shortcut-setup — frees the chords the editor needs from kitty
map ctrl+shift+g
map ctrl+shift+enter
map ctrl+shift+`
map shift+cmd+i
map opt+cmd+k
map cmd+l
map shift+cmd+z
map ctrl+super+z toggle_layout stack
map cmd+left
map cmd+right
map opt+left
map opt+right
map cmd+backspace
map opt+backspace
map shift+cmd+e
map shift+cmd+p
map ctrl+super+p kitten hints --type path --program -
map shift+cmd+c
map shift+cmd+h
map shift+cmd+n
